name: Build and Deploy to Private Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to private registry
      - name: Log in to private registry
        uses: docker/login-action@v2
        with:
          registry: registry.miljanrubezic.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Build and push Docker image with tag :latest
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: registry.miljanrubezic.com/nextjs-portfolio:latest
          build-args: |
            NEXT_PUBLIC_GA_ID=${{ secrets.NEXT_PUBLIC_GA_ID }}
            STRAPI_API_KEY=${{ secrets.STRAPI_API_KEY }}
            NEXT_PUBLIC_STRAPI_GRAPHQL_URL=${{ secrets.NEXT_PUBLIC_STRAPI_GRAPHQL_URL }}
            NEXT_PUBLIC_STRAPI_URL=${{ secrets.NEXT_PUBLIC_STRAPI_URL }}
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
            NEXT_PUBLIC_SENTRY_DSN=${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}

      # SSH into server and restart Docker Compose
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_SSH_KEY_PASS }}
          script: |
            cd /home/miljan
            docker compose pull nextjs
            docker compose up -d nextjs
            docker image prune -f
